---
title: "data_analysis"
author: "Hannah Schweren"
date: "2024-03-15"
output: html_document
---
```{r setup}
knitr::opts_knit$set(root.dir = '/Users/hannahschweren/Documents/Zukunft/Master/drittes semester/thesis/Code/thesis')
```


```{r}
library(legislatoR)
library(WikipediR)
library(rvest)
library(dplyr)
library(stringr) #für word count
library(ggplot2)
library(tm)
library(MatchIt)
library(quanteda)
library(purrr)
library(dplyr)
library(tidyverse)



```


load the data
```{r}
deu <- read.csv("data/clean/deu.csv")
matched_data <- read.csv(("data/clean/matched_data.csv"))
```



```{r}
prepare_corpus <- function(data_frame, text_column) {
  # Ensure the sex column is complete
  
  df_copy <- data_frame
  df_copy <- df_copy[complete.cases(df_copy$sex), ]
  
  # Convert the sex column to numeric (male = 0, female = 1)
  df_copy$sex <- ifelse(df_copy$sex == "male", 0, 1)
  
  # Summarize the text data by sex
  summary_df <- df_copy %>%
    group_by(sex) %>%
    summarise(text = paste(!!sym(text_column), collapse = " ")) %>%
    ungroup()
  
  # Create the corpus
  corpus_created <- corpus(summary_df, docid_field = "sex")
  
  return(corpus_created)
}

gender_neutral_replacements <- c(
  "Politikerin" = "Politiker",
  "Lehrerin" = "Lehrer",
  "Sprecherin" = "Sprecher",
  "Wissenschaftlerin" = "Wissenschaftler",
  "Direktkandidatin" = "direktkandidat",
  "Staatssekretärin" = "Staatssekretär",
  "Mitarbeiterin" = "Mitarbeiter",
  "Leiterin" = "Leiter",
  "Geschäftsführerin" ="Geschäftsführer",
  "Referentin" ="referent",
  "Spitzenkandidatin" ="Spitzenkandidat",
  "Staatsministerin" = "Staatsminister",
  "Ministerin" ="Minister",
  "Rechtsanwältin" ="Rechtsanwalt",
  "Statträtin" = "Stadtrat",
  "Generalsekretärin" ="Generalsekretär",
  "Senatorin" = "Senator",
  "Richterin" ="Richter",
  "Assistentin" = "assistent",
  "Bürgermeisterin" = "Bürgermeister",
  "Präsidentin" = "Präsident",
  "Vizepräsidentin" = "Vizepräsident",
  "Obfrau" = "Obmann",
  "Kandidatin"= "Kandidat",
  "Anwältin" = "Anwalt",
  "Apothekerin"="Apotheker",
  "Betreuerin" ="Betreuer",
  "Betriebswirtin" = "Btriebswirtin",
  "Dezernentin" ="Dezernent",
  "Diplom-Volkswirtin" ="Diplom-Volkswirt",
  "Direktorin" = "Direktor",
  "Dozentin" = "Dozent",
  "Erzieherin"="Erzieher",
  "Fachärztin" = "Facharzt",
  "Familientherapeutin" ="Familientherapeut",
  "Fotografin"="Fotograf",
  "Gründerin"="Gründer",
  "Hauswirtschaftsleiterin"="Hasuwirtschaftsleiter",
  "Journalistin" = "Journalist",
  "Juristin" = "Jurist",
  "Köchin" ="Koch",
  "Korrespondentin" ="Korrespondent",
  "Krankenpflegerin" = "Krankenpfleger",
  "Kunsthistorikerin" = "Kunsthistoriker",
  "Landrätin" ="Landrat",
  "Lebensgefährtin" = "Lebensgefährt",
  "Nachfolgerin" = "Nachfolger",
  "Oberbürgermeisterin" = "oberbürgermeister",
  "Postbeamtin" = "Postbeamte",
  "Schauspielerin" = "Schauspieler",
  "Schneiderin" = "Schneider",
  "Schriftstellerin" = "Schriftsteller",
  "Sekretärin"="Sekretär",
  "Sprachlehrerin"="Sprachlehrer",
  "Stadträtin" ="Stadtrat",
  "Supervisorin"="Supervisor",
  "Unternehmerin"="Unternehmer",
  "Verkäuferin"="Verkäufer",
  "Wirtschaftsingenieurin" ="Wirtschaftsingenieur",
  "Ärztin"="Arzt",
  "Gräfin" ="graf",
  "Partnerin"="partner",
  "Bundeskanzlerin"="Bundeskanzler",
  "Betriebswirtin"="betriebswirt",
  "industriekauffrau"="Industriekaufmann",
  "Einzelhandelskauffrau"="Einzelhandelskaufmann",
  "bankkauffrau"="Bankkaufmann",
  "Autorin" = "autor",
  "Stenotypistin" = "stenotypist",
  "Pädagogin"="Padagoge",
  "Stellvertreterin" ="Stellvertreter",
  "Bundesministerin" = "bundesminister",
  "Biologin" = "Biologe",
  "Schülerin" = "Schüler",
  "Verlegerin" = "Verleger",
  "Btriebswirtin" = "Betriebswirt",
  "Staatsrätin" = "Staatsrat",
  "Fabrikarbeiterin" = "Fabrikarbeiter",
  "Steuerberaterin" = "Steuerberater",
  "Buchhalterin" = "Buchhalter",
  "Architektin" = "Architekt",
  "Justizsenatorin" = "Justizsenator",
  "Hauswirtschaftslehrerin" = "hauswirtschaftslehrer",
  "Gymnasiallehrerin" = "Gymnasiallehrer",
  "Sozialarbeiterin" ="Sozialarbeiter",
  "Studienrätin" = "Studienrat",
  "Diplom-Kauffrau" = "Diplom-Kaufmann",
  "Soldatin" = "Soldat",
  "Landwirtin" = "Landwirt",
  "Redakteurin" = "Redakteur",
  "Professorin" = "Professor",
  "Notarin" ="Notar",
  "Prokuristin" = "Prokurist",
  "Diplom-Igenieurin" = "Diplom-Ingenieur",
  "Gewerkschaftssekretärin" = "Gewerkschaftssekretär",
  "Nationalsozialistin" = "Nationalsozialist",
  "Chefredakteurin" = "Chefredakteur",
  "Bundesgeschaftsführerin" = "Bundesgeschaftsfuhrer",
  "Kommunalpolitikerin" = "Kommunalpolitiker",
  "wurde" = "", #other words to remove
  "wurden" = "",
  "jahn" = "",
  "Gustav" =""
)

#namen extrahieren
first_words <- vapply(strsplit(deu$plain_text, "\\s+"), function(x) gsub("[,;:.!?]+$", "", x[1]), character(1))
second_words <- vapply(strsplit(deu$plain_text, "\\s+"), function(x) ifelse(length(x) > 1, gsub("[,;:.!?]+$", "", x[2]), ""), character(1))
#name_words <- unlist(strsplit(deu$name, " "))

months <- c("januar", "februar", "märz", "april", "mai", "juni", "juli", "august", "september", "oktober", "november", "dezember", "eins", "zwei", "drei", "vier", "fünf", "sechs", "sieben", "acht", "neun", "zehn", "1949–2002", "3-598-23782-0")

cities <- c("berlin", "heidelberg", "hamburg", "münchen", "köln", "frankfurt", 
            "stuttgart", "düsseldorf", "dortmund", "essen", "leipzig", 
            "bremen", "dresden", "hannover", "nürnberg", "duisburg", 
            "bochum", "wuppertal", "bielefeld", "bonn", "münster", 
            "karlsruhe", "mannheim", "augsburg", "wiesbaden", "gelsenkirchen", 
            "mönchengladbach", "braunschweig", "chemnitz", "kiel", "aachen", 
            "halle", "magdeburg", "freiburg im breisgau", "krefeld", 
            "lübeck", "oberhausen", "erfurt", "mainz", "rostock", "kassel", 
            "hagen", "hamm", "saarbrücken", "mülheim an der ruhr", "potsdam", 
            "ludwigshafen", "oldenburg", "leverkusen", "osnabrück", "bonn")

custom.stopwords <- read.csv("data/raw/SW-DE-RS_v1-0-0_Datensatz.csv")
custom.stopwords <- unlist(custom.stopwords)
custom.stopwords <- unname(custom.stopwords)
custom.stopwords <- as.character(custom.stopwords)
custom.stopwords <- custom.stopwords[custom.stopwords!=""]

##############namen problem
words_to_remove <- unique(c(first_words, second_words, months, cities, stopwords("de")))

#words_to_remove <- unique(c(name_words, stopwords("de")))


process_corpus <- function(corpus, gender_neutral_replacements, words_to_remove) {
  # Tokenizing the corpus with specific removals and replacements
  tokens <- tokens(corpus, remove_punct = TRUE, remove_numbers = TRUE, remove_symbols = TRUE) %>%
    tokens_tolower() %>%
    tokens_replace(pattern = names(gender_neutral_replacements), replacement = gender_neutral_replacements, case_insensitive = TRUE) %>%
    tokens_remove(pattern = words_to_remove, padding = FALSE) %>%
    tokens_remove(pattern=custom.stopwords)%>%
    tokens_wordstem(language = "german")%>%
    tokens_remove(pattern = words_to_remove, padding = FALSE)

  
  # Creating the DFM
  dfmat <- dfm(tokens)
  
  # Printing the result to check
  print(dfmat)
  
  # Converting the DFM to a data frame
  corpus_df <- convert(dfmat, to = "data.frame")
  
  # Setting the first column as row names
  rownames(corpus_df) <- corpus_df[, 1]
  
  # Removing the first column from the DataFrame
  corpus_df <- corpus_df[, -1]
  
  # Keeping only words that appear in both genders by filtering out columns with zeros
  zero_count_per_column <- colSums(corpus_df == 0)
  corpus_common <- corpus_df[, zero_count_per_column == 0]
  
  # Transposing the matrix to swap rows and columns
  corpus_transposed <- t(corpus_common)
  
  # Converting the transposed matrix back to a DataFrame and adjusting columns
  corpus_transposed <- as.data.frame(corpus_transposed)
  corpus_transposed$word <- rownames(corpus_transposed)
  rownames(corpus_transposed) <- NULL
  colnames(corpus_transposed) <- c("male", "female", "word")
  
  return(corpus_transposed)
}



calculate_pmi_and_filter <- function(corpus_transposed, corpus_name, min_p = 0.0002) {
  # Calculate total counts
  total_male_count <- sum(corpus_transposed$male)
  total_female_count <- sum(corpus_transposed$female)
  total_count <- total_male_count + total_female_count

  # Calculate probabilities for each class
  p_c_male <- total_male_count / total_count
  p_c_female <- total_female_count / total_count

  # Add PMI calculations to the DataFrame
  pmi_df <- corpus_transposed %>%
    mutate(p_w = (male + female) / total_count,
           p_male_w = male / total_count,
           p_female_w = female / total_count,
           PMI_male = log(p_male_w / (p_w * p_c_male)) / -log(p_male_w),
           PMI_female = log(p_female_w / (p_w * p_c_female)) / -log(p_female_w))

  # Filter for words with PMI value greater than 0.02 to only get relevant results
  filtered_female <- pmi_df %>%
    filter(p_w > min_p & PMI_female > 0.02) %>%
    arrange(desc(PMI_female))%>%
    head(100)

  filtered_male <- pmi_df %>%
    filter(p_w > min_p & PMI_male > 0.02) %>%
    arrange(desc(PMI_male))%>%
    head(100)


  # Save to CSV (commented out)
  write.csv(filtered_female, sprintf("data/pmi_list/%s_pmi_female.csv", corpus_name), row.names = FALSE)
  write.csv(filtered_male, sprintf("data/pmi_list/%s_pmi_male.csv", corpus_name), row.names = FALSE)

  # Return a list containing both dataframes
  return(list(top_female = filtered_female, top_male = filtered_male))
}
```


apply functions:

```{r}


# #whole sample, life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(deu, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "deu_life")
#
# #matched sample, old life section########################################################################################
# # Step 1:
corpus <- prepare_corpus(matched_data, "extracted_text_old")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "matched_old_life")

# #matched sample, new life section########################################################################################
# Step 1:
corpus <- prepare_corpus(matched_data, "extracted_text_new")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "matched_new_life")


# #matched sample, old career section########################################################################################
# # Step 1:
corpus <- prepare_corpus(matched_data, "career_text_old")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "matched_old_career")

# #matched sample, new career section########################################################################################
# Step 1:
corpus <- prepare_corpus(matched_data, "career_text_new")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "matched_new_career")

# #whole 

# #whole sample career/party section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(deu, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "deu_career")
# 
# #matched data life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(matched_data, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "matched_life")
# 
# #matched data career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(matched_data, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "matched_career")
# 
# ##################################################################################################################################
# 
# #cohort 1 career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(first_cohort, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "1_cohort_career")
# 
# 
# #cohort 2 career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(second_cohort, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "2_cohort_career")
# 
# 
# #cohort 3 career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(third_cohort, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "3_cohort_career")
# 
# 
# #cohort 4 career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(fourth_cohort, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "4_cohort_career")
# 
# 
# #cohort 5 career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(fifth_cohort, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "5_cohort_career")
# 
# #cohort 1 life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(first_cohort, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "1_cohort_life")
# 
# 
# #cohort 2 life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(second_cohort, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "2_cohort_life")
# 
# 
# #cohort 3 life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(third_cohort, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "3_cohort_life")
# 
# 
# #cohort 4 life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(fourth_cohort, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "4_cohort_life")
# 
# 
# #cohort 5 life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(fifth_cohort, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "5_cohort_life")
# 
# 
# ##################################################################################################################################

#cohorts - 3 groups
#cohort 3 life section########################################################################################
# Step 1:
corpus <- prepare_corpus(cohort3, "extracted_text")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "third_cohort_life")


#cohort 2 life section########################################################################################
# Step 1:
corpus <- prepare_corpus(cohort2, "extracted_text")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "second_cohort_life")

#cohort 1 life section########################################################################################
# Step 1:
corpus <- prepare_corpus(cohort1, "extracted_text")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "first_cohort_life")


#cohort 3 career section########################################################################################
# Step 1:
corpus <- prepare_corpus(cohort3, "career_text")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "third_cohort_career")

#cohort 2 career section########################################################################################
# Step 1:
corpus <- prepare_corpus(cohort2, "career_text")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "second_cohort_career")

#cohort 1 career section########################################################################################
# Step 1:
corpus <- prepare_corpus(cohort1, "career_text")

# Step 2:
corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)

# Step 3:
results <- calculate_pmi_and_filter(corpus_transposed, "first_cohort_career")

# 
# #afd life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(afd_df, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "afd_life")
# 
# #cdu/csu life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(cdu_csu_df, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "cdu_csu_life")
# 
# #greens life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(greens_df, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "greens_life")
# 
# #left life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(left_df, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "left_life")
# 
# #fdp life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(fdp_df, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "fdp_life")
# 
# #spd life section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(spd_df, "extracted_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "spd_life")
# 
# #afd career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(afd_df, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "afd_career")
# 
# #cdu/csu career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(cdu_csu_df, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "cdu_csu_career")
# 
# #greens career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(greens_df, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "greens_career")
# 
# #left career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(left_df, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "left_career")
# 
# #fdp career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(fdp_df, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "fdp_career")
# 
# #spd career section########################################################################################
# # Step 1: 
# corpus <- prepare_corpus(spd_df, "career_text")
# 
# # Step 2: 
# corpus_transposed <- process_corpus(corpus, gender_neutral_replacements, words_to_remove)
# 
# # Step 3: 
# results <- calculate_pmi_and_filter(corpus_transposed, "spd_career")

```

Analysis for different cohorts - create dataframe per cohort
```{r}

#split in relatively equaly sized cohorts
# cohort_assignment <- function(year) {
#   if(year < 1939) {
#     return("first_cohort")
#   } else if(year >= 1939 & year <= 1949) {
#     return("second_cohort")
#   } else if(year >= 1949 & year <= 1959) {
#     return("third_cohort")
#   } else if(year >= 1959 & year <= 1969) {
#     return("fourth_cohort")
#   } else {
#     return("fifth_cohort")
#   }
# }

cohort_assignment <- function(year) {
  if(year < 1949) {
    return("cohort1")
  } else if(year >= 1949 & year <= 1969) {
    return("cohort2")
  } else {
    return("cohort3")
  }
}


# Anwenden der Funktion auf den birthyear, um die Kohortenzugehörigkeit als Vektor zu erhalten
cohort_vector <- sapply(matched_data$birthyear, cohort_assignment)

# Aufteilen des DataFrames in eine Liste von DataFrames basierend auf dem Kohortenvektor
list_of_dfs <- split(matched_data, cohort_vector)

# Zugriff auf die separaten DataFrames direkt aus der Liste
# first_cohort <- list_of_dfs$first_cohort
# second_cohort <- list_of_dfs$second_cohort
# third_cohort <- list_of_dfs$third_cohort
# fourth_cohort <- list_of_dfs$fourth_cohort
# fifth_cohort <- list_of_dfs$fifth_cohort

cohort1 <- list_of_dfs$cohort1
cohort2 <- list_of_dfs$cohort2
cohort3 <- list_of_dfs$cohort3

```



Analysis for different parties - create dataframe per party
```{r}
parties <- c("FDP", "AfD", "BÜNDNIS 90/DIE GRÜNEN", "CDU", "CSU", "SPD", "DIE LINKE")

# Liste, um die separaten DataFrames zu speichern
party_dfs <- list()

# Schleife über die Namen der Parteien
for(party in parties) {
  if(party == "CDU" || party == "CSU") {
    # Füge Daten für CDU und CSU zusammen, falls noch nicht geschehen
    if(!"CDU_CSU" %in% names(party_dfs)) {
      party_dfs[["CDU_CSU"]] <- matched_data[matched_data$party %in% c("CDU", "CSU"), ]
    }
  } else {
    # Erstelle einen DataFrame für jede andere Partei
    party_dfs[[party]] <- matched_data[matched_data$party == party, ]
  }
}

# Zugriff auf den kombinierten DataFrame von CDU und CSU
cdu_csu_df <- party_dfs[["CDU_CSU"]]
greens_df <- party_dfs[["BÜNDNIS 90/DIE GRÜNEN"]]
left_df <- party_dfs[["DIE LINKE"]]
fdp_df <- party_dfs[["FDP"]]
spd_df <- party_dfs[["SPD"]]
afd_df <- party_dfs[["AfD"]]

```