---
title: "first steps"
author: "Hannah Schweren"
date: "2024-01-04"
output: html_document
---

```{r}
library(legislatoR)
library(WikipediR)
library(rvest)
library(dplyr)
library(stringr) #für word count
library(ggplot2)

```

```{r}
deu_core <- get_core(legislature = "deu")
#deu_core <- head(deu_core)
deu_core_alive <- deu_core %>% filter(is.na(death))

deu_pol <- get_political(legislature = "deu")
```

```{r}
#alle backlinks, die auf die Seite verweisen - vergleich Frauen&Männer?
all_bls <- page_backlinks("de","wikipedia", page = "Achim_Großmann")
```

```{r}

#einzelne person:

wp_content <- page_content("de","wikipedia", page_name = "Andreas_Wagner_(Politiker,_1972)")

html_text(read_html(wp_content$parse$text$`*`))
```

```{r}
###########functions

###text retreival

text_pipeline <- function(page_name) {
  Sys.sleep(runif(1, 1, 2))
  
  # Check if page_name is missing
  if (is.na(page_name) || page_name == "") {
    return("No Wikipedia page name provided or missing.")
  }
  
  # Try fetching Wikipedia content
  tryCatch({
    wp_content <- WikipediR::page_content("de", "wikipedia", page_name = page_name)
    plain_text <- html_text(read_html(wp_content$parse$text$`*`))
    return(plain_text)
  }, error = function(e) {
    return(paste("Error fetching content for page:", page_name))
  })
}



###word count

count_words <- function(text) {
  words <- str_extract_all(text, "\\b\\w+\\b")[[1]]
  return(length(words))
}

```

```{r}

#iterate over dataset
deu_alive_text <- deu_core_alive %>%
  mutate(plain_text = sapply(wikititle, text_pipeline))

# 'plain_text' enthält nur die plain text Versionen der Wikipedia-Artikel

```

```{r}
deu_alive_text$Word_Count <- sapply(deu_alive_text$plain_text, count_words)


#save the current state of scraped data
write.csv(deu_alive_text, file = "")

```

```{r}
ggplot(deu_alive_text, aes(x = Word_Count, fill = sex)) +
  geom_bar(stat = "count", position = "dodge") +
  labs(x = "Word_Count", y = "Count", title = "Distribution of word count by Gender") +
  scale_fill_manual(values = c("blue", "pink")) + # Farben anpassen
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
deu_history <- get_history(legislature = "deu")

#join relevant data

deu_edits <- deu_history %>%
  left_join(select(deu_core, pageid, sex, wikititle), by = "pageid")
```

```{r}

###durchschnittl.edits pro monat pro politiker*in

########women#############

# Umwandlung des Timestamp in ein Datumsobjekt
deu_edits$timestamp <- as.Date(deu_edits$timestamp)

# Extrahieren von Monat und Jahr
deu_edits$Month <- format(deu_edits$timestamp, "%Y-%m")

deu_edits_fem <- deu_edits %>% filter(sex == "female")

# Gruppieren und Zusammenfassen
edits_per_politician_month_fem <- deu_edits_fem %>%
  group_by(wikititle, Month) %>%
  summarise(Edits_Count = n())

# Durchschnitt pro Monat pro Politikerin berechnen
avg_edits_per_politician_month_fem <- edits_per_politician_month_fem %>%
  group_by(wikititle) %>%
  summarise(Avg_Edits_Per_Month = mean(Edits_Count))

#########men############


# Extrahieren von Monat und Jahr

deu_edits_male <- deu_edits %>% filter(sex == "male")

# Gruppieren und Zusammenfassen
edits_per_politician_month_male <- deu_edits_male %>%
  group_by(wikititle, Month) %>%
  summarise(Edits_Count = n())

# Durchschnitt pro Monat pro Politikerin berechnen
avg_edits_per_politician_month_male <- edits_per_politician_month_male %>%
  group_by(wikititle) %>%
  summarise(Avg_Edits_Per_Month = mean(Edits_Count))

##########################################################################################################################################
###durchschnittl.anzahl edits pro politiker*in


# Gruppieren und Zusammenfassen
edits_per_politician <- deu_edits %>%
  group_by(wikititle) %>%
  summarise(Total_Edits = n())

# Durchschnittliche Gesamtbearbeitungen pro Politiker berechnen
average_edits_per_politician <- mean(result$Total_Edits)

# Ergebnisse anzeigen
print(average_edits_per_politician)
```

```{r}

combined_data <- rbind(
  cbind(avg_edits_per_politician_month_fem, Gender = "Female"),
  cbind(avg_edits_per_politician_month_male, Gender = "Male")
)

combined_data$Avg_Monthly_Edits_Grouped <- cut(combined_data$Avg_Edits_Per_Month, breaks = c(0, 5, 10, 15, 20), labels = c("0-5", "6-10", "11-15", "16-20"))


ggplot(combined_data, aes(x = as.factor(Avg_Monthly_Edits_Grouped), fill = Gender)) +
  geom_bar(stat = "count", position = "dodge") +
  labs(x = "Average Monthly Edits", y = "Count", title = "Distribution of Average Monthly Edits by Gender") +
  scale_fill_manual(values = c("blue", "pink")) + # Farben anpassen
  theme_minimal()

ggplot(combined_data, aes(x = Avg_Monthly_Edits_Grouped, fill = Gender)) +
  geom_bar(stat = "count", position = "dodge") +
  labs(x = "Average Monthly Edits (Grouped)", y = "Count", title = "Distribution of Average Monthly Edits by Gender") +
  scale_fill_manual(values = c("blue", "pink")) + # Farben anpassen
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

barplot
```

