---
title: "PAP"
author: "Hannah Schweren"
date: "2024-01-22"
bibliography: bibliographie_thesis_test.bib
output: html_document
---


# 1. Summary: 
# Describe the main goals of the project, what is the scientific question you are trying to answer, and how will you go about it in no more than 300 words.

The project is following the goal of measuring gender bias in politician's wikipedia biographies in an international context. Wikipedia is  the seventh most visited website worldwide in 2022 and used by over 4 billion unique global visitors a month [Source]. A lot of people use it to quickly get information about celebrities, artists, politicians etc. Thus, it is very important that wikipedia's content is as neutral as possible and does not maintain or even reinforce societal biases. One could argue that this is even more important for the subgroup of politicians as wikipedia's representation of politicians influence citizens when they look for information before elections in democratic processes. Previous research has shown that there is a considerate lexical gender bias in biographies in wikipedia. I want to focus on one specific group of biographies, namely politicians, and find out if general conclusions are valid for this specific group as well. Further, a lot of research focuses on English articles. I analyze all politicians’ texts in their national language and thereby I aim at comparing the extent of gender bias in different countries. My research questions are thus:

QR1: Can results of previous research concerning lexical gender bias in biographies be applied to the subgroup of politican's biographies?

RQ2: How do the results vary in the international context?

I aim at answering those questions by using the available data from the “Comparative Legislator Database” containing politicians, their wikipedia names and some additional information (like traffic, edits etc.) from 9 countries (‘aut’, ‘can’, ‘cze’, ‘esp’, ‘fra’, ‘deu’, ‘irl’, ‘sco’, ‘gbr’, ‘usa_house’, or ‘usa_senate’). First I retrieve all articles in their original language. Then I plan to assess the extent of the articles’ gender bias first by using simple descriptive indicators land second by using mutual pointwise information.

https://www.statista.com/statistics/1201880/most-visited-websites-worldwide/
https://www.statista.com/statistics/1259907/wikipedia-website-traffic/


# 2. Motivation and background: 
## Why is this research question interesting to you, how does your background align with the topic, and what skills or knowledge do you want to acquire by doing the work that is valuable for your future career?

This research question is interesting to me as I have been interested in gender equality topics for several years now, having dealt with the child penalty during my studies, working with the issue of the gender care gap in my student job and overall being motivated to learn more about gender related inequalities. In the scope of my masters thesis, I want to learn more about such issues in the online world and use the techniques that I have acquired during my master at Hertie School. Thus, this research topic  is very exciting for me and I am curious to dive deeper into gender inequalities in the political area. 
The category of politicians is specifically interesting to me, being a public policy student. Inequalities in this sphere are particularly interesting as politicians represent all citizens and have a real life impact. So, a misrepresentation in the form of gender bias can be seen as a problem for democratic processes, as citizens use online platforms like Wikipedia to inform themselves, expecting a neutral voice. 
I expect to acquire skills in the field of text data processing which will be advantageous for my future career. I aspire to work in a political sphere after my graduation and a lot of political data is in the form of text. Thus, I hope to gain some knowledge that will be useful for my next steps after university.



# 3. Introduction: 
## Discuss what is the context for the research question and what previous work has been conducted in this area. Please discuss 1-3 key academic papers that are most relevant to your project. You should summarise the papers, the goal and achievement of the papers, data and methods used in the papers, and how they relate to your proposed topic. Also include references to other relevant papers in the introduction as needed.

The area of research focussing on gender bias in wikipedia has developed in the last few years and is mainly focussed on English articles and general biographies (not focussing on one specific category of people). The following 3 papers are of a main interest, when dealing with lexical gender bias on wikipedia:

1. "Women through the glass ceiling: gender asymmetries in Wikipedia"
(Reference) Wagner et al. aim at assessing potential gender inequalities in english Wikipedia articles along different dimensions using the The DBpedia dataset. Adopting an open vocabulary approach, they consider n-grams with n ≤ 2 to encompass multi-word concepts. The analysis involves exploring the association between the top 200 n-grams for each gender and the four topics (gender, relationship, family, or other), with Pointwise Mutual Information used for ranking the n-grams for men and women. Among other findings, they achieve to show that family-, gender-, and relationship-related topics are more present in biographies about women. Which is a clear indicator for a lexical bias.

2. “First Women, Second Sex: Gender Bias in Wikipedia”
(reference) deal with the question wether there is a gender bias in user-generated characterizations of men and women in Wikipedia and if so, how to identify and quantify it. For this, they use the DBPedia 2014 dataset and The Wikipedia English Dump of October 2014. They rely on several approaches to estimate the gender bias in the articles, among others they use Pointwise mutual information and find that “Sex-related content is more frequent in women biographies than men’s, while cognition-related content is more highlighted in men biographies than women’s”.

3. “It's a Man's Wikipedia? Assessing Gender Inequality in an Online Encyclopedia” 
(Reference) As in the previous paper, Wagner et al. assess potential gender inequalities in Wikipedia articles along different dimensions (coverage bias, structural bias, lexical bias and visibility bias). In this paper they also include several language editions and compare their results with the Gender Inequality Index of the World Economic Form (WMF) (Schwab et al. 2013) to  draw a connection between bias in the offline and online world. The authors use collections of notable people as reference datasets, crawling the articles for the dataset’s individuals. To assess the amount of lexical bias, they, again, use an open vocabulary approach. Instead of an analysis of the PMI, as in the previous paper, this time  they use tfidf scores to train a Naive Bayes classifier. The classifier employs log likelihood ratios (L(word, g)) to assess which words are most effective in discerning the gender of the person mentioned in an article.The lexical analysis shows “that articles about women tend to emphasize the fact that they are about a women (...) while articles about men don’t contain words like “man”, “masculine” or “gentleman”.”



# 4. Research question: 
## What research question will you try to answer with the thesis and what is the main approach to address the question? If you are testing hypotheses, specify them here as well

My Research Questions are the following: 

QR1: Can results of previous research concerning lexical gender bias in biographies be applied to the subgroup of politican's biographies?

RQ2: How do the results vary in the international context?

The approach reflect previous research on this topic, specifying the examined group, focussing on politicians, instead of generic biographies on wikipedia. I want to see if the backround of being a politician maybe changes the extend of gender bias, as 


# 5. Data and methods: 
## What data and methods are you planning to use? Please be as specific as possible in what you want to approach to achieve to facilitate further discussion whether it is appropriate for answering the research question. Also mention alternative methods, especially if you are unsure about which method is best. This is the core part of the PAP!